#!/usr/bin/env python
import sys
import traceback
from snort import snortdb
import datetime

def check(sensor,timeout):
    s = snortdb.sdb()
    last = s.get_last_event_time_for_sensor(sensor)
    #this is probably really stupid
    last = last.replace(tzinfo=None)
    now = datetime.datetime.now()
    offset = datetime.timedelta(minutes=timeout)
    if now - last > offset:
        print 'Error: last updated: %s' % last
        return 2
    else:
        print 'OK: last updated: %s' % last
    return 0

def main():
    if len(sys.argv) <3 :
        print 'usage %s sensor_hostname timeout' % sys.argv[0]
        print '(timeout in minutes)'
        sys.exit(1)
    sensor = sys.argv[1]
    timeout = int(sys.argv[2])
    try:
        num = int(sys.argv[3])
    except:
        num = 1
    for x in range(num):
        try:
            code = check("%s-%d" % (sensor, x), timeout)
        except Exception, e:
            print "Error"
            traceback.print_exc()
            sys.exit(2)
    sys.exit(code)

if __name__ == "__main__":
    main()
