#!/usr/bin/env python 
import sys
from snort import snortdb

def format_data(data):
    if not data:
        return ''
    lines = data.splitlines()
    return '  ' + '\n  '.join(lines)

def show_ip(ip,dest=None,start_date=None,end_date=None,show_data=False,limit=1000):
    s = snortdb.sdb()
    s.setlimit(limit)

    if start_date:
        s.setwhere(start_date,end_date)

    if not dest:
        alerts = s.find(host=ip)
    else:
        alerts = s.find(hostpair=(ip,dest))
    for x in alerts:
        x['sig'] = x['sig'].replace("BLEEDING-EDGE ",'')
        if len(x['sig']) > 40:
            x['sig'] = x['sig'][0:40] + '..'
        print "%(timestamp)s %(ip_src)s:%(sport)s -> %(ip_dst)s:%(dport)s %(sig)s" % x
        if show_data:
            print format_data(x['data'])

def main():
    from optparse import OptionParser
    parser = OptionParser()
    parser.add_option("-i", "--ip",        dest="ip",         action="store", help="ip address")
    parser.add_option("-d", "--dest",      dest="dest",       action="store", help="destination IP") 
    parser.add_option("-s", "--startdate", dest="start_date", action="store", help="start date")
    parser.add_option("-e", "--enddate",   dest="end_date",   action="store", help="end date")
    parser.add_option("-o", "--showdata",  dest="show_data",  action="store_true", help="show packet contents",default=False)
    parser.add_option("-l", "--limit",     dest="limit",      action="store", help="limit number of alerts", default=1000)

    (options, args) = parser.parse_args()

    if not (options.ip):
        sys.stderr.write("Specify ip address\n")
        parser.print_help()
        sys.exit(1)

    #probably shouldn't do this, but it works :-)
    show_ip(**options.__dict__)

if __name__ == "__main__":
    main()
